version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    volumes:
      - images_volume:/app/images
    networks:
      - app_network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_BASEURL=/api
    networks:
      - app_network
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend

  db:
    container_name: 'db'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - app_network
    ports:
      - '5432:5432'

networks:
  app_network:
    driver: bridge

volumes:
  images_volume:
